version: '3.1'
services:
  nginx:
    container_name: MEAN-NGINX
    build:
      context: ./docker
      dockerfile: nginx_docker
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config-nginx:/etc/nginx/conf.d
  node:
    container_name: MEAN-NODE
    build:
      context: ./docker
      dockerfile: node_docker
    ports:
      - 3000:3000
  mongo:
    container_name: MEAN-MONGO
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27027:27017
    volumes:
      - mongodb_data:/data/db
      - ./config-mongo:/data/configdb
volumes:
  mongodb_data: